workers/openrelik-worker-analyzer-config: 'workers/openrelik-worker-analyzer-config/**'
workers/openrelik-worker-containers: 'workers/openrelik-worker-containers/**'
workers/openrelik-worker-floss: 'workers/openrelik-worker-floss/**'
workers/openrelik-worker-os-creds: 'workers/openrelik-worker-os-creds/**'
workers/openrelik-worker-yara: 'workers/openrelik-worker-yara/**'