workers/analyzer-config: 'workers/analyzer-config/**'
workers/analyzer-logs: 'workers/analyzer-logs/**'
workers/bulkextractor: 'workers/bulkextractor/**'
workers/capa: 'workers/capa/**'
workers/chromecreds: 'workers/chromecreds/**'
workers/containers: 'workers/containers/**'
workers/cloud-logs: 'workers/cloud-logs/**'
workers/dfindexeddb: 'workers/dfindexeddb/**'
workers/duckdb: 'workers/duckdb/**'
workers/entropy: 'workers/entropy/**'
workers/exif: 'workers/exif/**'
workers/extraction: 'workers/extraction/**'
workers/floss: 'workers/floss/**'
workers/grep: 'workers/grep/**'
workers/llm: 'workers/llm/**'
workers/os-creds: 'workers/os-creds/**'
workers/photorec: 'workers/photorec/**'
workers/strings: 'workers/strings/**'
workers/timesketch: 'workers/timesketch/**'
workers/yara: 'workers/yara/**'
workers/plaso: 'workers/plaso/**'
workers/hasher: 'workers/hasher/**'
